### ISSUE TITLE
'Func' objects behaving weirdly

### ISSUE THREAD

**Issue by Allyally** [fasterthanlime/rock#875]
Firstly, I had this short piece of code:
```
myFunc: Func(Int)
myFunc_imp: func (i: Int) {
	"%d" printfln(i)
}
main: func {
	myFunc = myFunc_imp
	myFunc(10)
}
```
The compiler throws a 'No such function' error on `myFunc(10)`, but can however, be worked around like this:
```
f := myFunc
f(10)
```
Which is just bizarre. Seems like it has difficulty with global Func objects.

The second issue is with Func objects as generic types. For example I can make an ArrayList of Func, but I cannot add items to it:
```
saySomething: func {
	"Hi!" println()
}	
main: func {
	ar := ArrayList<Func> new()
	ar add(saySomething)
}
```

This also gives a 'No such function' error. This can be worked around with a container for that function:
```
FuncContainer: class <T> {
	f: Func(T)
	init: func(=f)
}
saySomething: func(i: Int) {
	"%d" printfln(i)
}
main: func {
	fObj := FuncContainer<Int> new(saySomething)
	ar := ArrayList<FuncContainer<Int>> new()
	ar add(fObj)
	ar get(0) f(12)
}
```

This compiles fine, but however it does not print 12, but instead '2686632'.
As @geckojsc put it "I imagine the generic type bundles some extra information along with it making it incompatible with regular functions"

It's also worth mentioning, this is only a problem with generic types. Change it to Int only functions, and it prints 12 just fine.

**Comment by zhaihj** [comment]
About this:

    FuncContainer: class <T> {
        f: Func(T)
        init: func(=f)
    }
    saySomething: func(i: Int) {
        "%d" printfln(i)
    }
    main: func {
        fObj := FuncContainer<Int> new(saySomething)
        ar := ArrayList<FuncContainer<Int>> new()
        ar add(fObj)
        ar get(0) f(12)
    }

It is a issue that has been reported (See here: https://github.com/fasterthanlime/rock/issues/804 ).

This problem is that you defined function as generic but implement it without generic.
Currently any generic variable will be passed by reference, it means that when you call 
`FunctionContainer->f(12)`, rock will generate code like `temp: Int = 12; FunctionContainer->f(&temp)`.
However, `f` points to `saySomething`, which is a normal function, so you will get the address of parameter.

The solution is simple: just declare parameters by reference:

    saySomething: func(i: Int@) {
        "%d" printfln(i)
    }

**Comment by Allyally** [comment]
Strangley, I tried the same code again this morning and it worked without your suggested fix.
