### ISSUE TITLE
Emacs Mode for Rock

### ISSUE THREAD

**Issue by ejmr** [fasterthanlime/rock#883]
It would be nice to have a simple Emacs mode for this programming language.  I will write it in the near future and submit it as pull request, unless there are any objections to including such a thing within the project.

**Comment by fasterthanlime** [comment]
As per http://ooc-lang.org/docs/tools/editors/#emacs there is already an ooc mode, although it hasn't been touched since 2010 and could certainly use some love!

Even the vim syntax and the pygments highlight file (what GitHub uses to do syntax colouring) could use some love, I don't think they support new stuff like floating point literal support.

It would be easier to have comprehensive syntax files if I was doing a better job of maintaining the docs! But I'll be happy to answer any questions (by looking at [the grammar](https://github.com/fasterthanlime/nagaqueen), as a last resort.)

**Comment by fasterthanlime** [comment]
(So, closing, but feel free to open a pull request on https://github.com/fasterthanlime/ooc-lang.org if you have a more updated fork of ooc-mode — provided @nixeagle isn't interested in shepherding it anymore!)

**Comment by ejmr** [comment]
Thanks for the info!  I'll take a look at the existing `ooc-mode` and hack on it in my spare time.  If I make any significant improvements I'll be sure to send them your way.
