### ISSUE TITLE
super() may pick incorrect function 

### ISSUE THREAD

**Issue by zhaihj** [fasterthanlime/rock#905]
Test code:
```ooc

Foo: class{
    init: func

    test: func(a: Int, c: SizeT){
        "foo get: %d, %d" printfln(a, c)
    }
}

Bar: class extends Foo{
    init: func
    test: func~somesuffix(a: Int, c: SizeT){
        "bar get: %d, %d" printfln(a, c)
        super(a,c)
    }
}

Baz: class extends Bar{
    init: func

    test: func(a: Int, c: SizeT){
        "calling super..." printfln()
        super(a, c)
    }
}

test := Baz new()

test test(10, 100)
```

Expected:

```
calling super...
bar get: 10, 100
foo get: 10, 100
```

Got:

```
calling super...
foo get: 10, 100
```

Because functions with (different) suffixes will have lower scores regardless of which level they are.
Should this be treated as bug,  or just a feature?

related issue in ooc-kean(fixed): https://github.com/cogneco/ooc-kean/issues/128
my patch: https://github.com/zhaihj/rock/commit/9ae66dcbb07509710a7224345142068c1cb1b800

**Comment by fasterthanlime** [comment]
I'm conflicted on this. My original vision of suffixes was that they were used to mark `variants` of functions, the suffix-less being the original / main version. Which explains why suffix-less functions get a higher score.

Your patch gives a higher score to functions that are closer in the type hierarchy right? Although it does fix that particular test case, doesn't it make function scoring even more confusing?

I genuinely don't know what the right thing to do is, here.

**Comment by davidhesselbom** [comment]
In other languages I've used, to overload a function, you give two functions the same name but different signatures. In ooc, that doesn't work, so you use suffixes instead. Coming from C#, I still *think of them* as overloads, though, so the above behavior is confusing to me, because I expect the `super` call to match on signature. I don't know if this helps at all with figuring out what the right thing to do is, but that's how one person feels about it. Personally, I don't really see a point in having several functions with the same name and the same signature in the same class that do different things, so suffixes are a bit of an odd solution to me.

**Comment by fasterthanlime** [comment]
@davidhesselbom The original intent behind suffixes was to have sane mangling of names in the generated C. Arguably, that's still useful.

**Comment by davidhesselbom** [comment]
Sure. 

Thinking out loud, what if rock was to disallow having several functions with the same name and the same signature, but that have different suffix? Or at least give a warning?

**Comment by davidhesselbom** [comment]
Or, throw a warning that a call like `super(a, c)` in the `Baz` class above is ambiguous?

**Comment by davidhesselbom** [comment]
In my experience, it's often easier to come up with good ideas when people around you come up with bad ones. 

* hides *

**Comment by fasterthanlime** [comment]
> throw a warning

It's not actually a bad idea, was the thing that came to mind when reading the code in this thread. The code in this thread looks silly to me, but hey who am I to decide what users can and can't do.

We don't have a way to disable warnings yet, though, so then we're gonna get complaints about the warning people can't disable.

**Comment by davidhesselbom** [comment]
It may look silly, but I've spent a lot of time debugging code that didn't work the way I wanted it to due to this exact behavior, all this because I wrongly assumed that `super` with a given sequence of argument types would call that function in its immediate parent class regardless of suffixes.

If a warning can be silenced, that would imply that rock isn't actually picking the *wrong* function, but a function that *some people wouldn't expect it to*. If the behavior isn't wrong, you shouldn't need a warning for it. Since the behavior is unlike what many people might expect, though, the documentation could be clearer on that point. @zhaihj's example above could go into the documentation as an example of how not to write ooc code.

**Comment by fasterthanlime** [comment]
> I wrongly assumed that super with a given sequence of argument types would call that function in its immediate parent class regardless of suffixes.

That sounds like a separate issue. Afaict it's not clearly specified in the doc, but it would make sense to limit it to the immediate parent. That sounds like a much cleaner fix than a layer system

**Comment by davidhesselbom** [comment]
> That sounds like a separate issue.

In @zhaihj's example, the `super(a, c)` call in `Baz` calls `test(a, c)` not in its parent class `Bar`, but in its grandparent class `Foo`, despite having the same sequence of argument types (`Int`, `SizeT`) as `test` in its parent class `Bar`, and this happens because of differing suffixes (`~somesuffix` vs. no suffix). This can be described as "rock picking the incorrect function" if you assume that suffixes shouldn't matter as long as the signature is the same. How is that a separate issue?

**Comment by fasterthanlime** [comment]
It's a separate issue because the actual bug is "there is no language spec that says what needs to be picked in that case", whereas rock does exactly what I designed it to do, afaict.

**Comment by davidhesselbom** [comment]
Oh you mean

> Since the behavior is unlike what many people might expect, though, the documentation could be clearer on that point. @zhaihj's example above could go into the documentation as an example of how not to write ooc code.

is a separate issue. Agreed.

**Comment by fasterthanlime** [comment]
What actually needs to be done is:

  * Say on the website that `super()` only ever calls methods from the direct parent*
  * Make rock adhere to that behavior
  * Original issue doesn't exist anymore

**Comment by davidhesselbom** [comment]
Alright. So then, after all that has been done, in the above example, you would get the expected output 
```
calling super...
bar get: 10, 100
foo get: 10, 100
```
and if `Bar` has no implementation at all of `test` (but `Foo` still does), you get some compiler error that complains `Bar` has no implementation of `test`?

**Comment by zhaihj** [comment]
A more confusing case:(just add suffix to `Baz test`)

```ooc
Foo: class{
    init: func

    test: func(a: Int, c: SizeT){
        "foo get: %d, %d" printfln(a, c)
    }
}

Bar: class extends Foo{
    init: func
    test: func~somesuffix(a: Int, c: SizeT){
        "bar get: %d, %d" printfln(a, c)
        super(a,c)
    }
}

Baz: class extends Bar{
    init: func

    test: func~somesuffix(a: Int, c: SizeT){
        "calling super..." printfln()
        super(a, c)
    }
}

test := Baz new()

test test(10, 100)
```

The output of this code is:
```
foo get: 10, 100
```

However, we are calling `test` on an instance from `Baz`.
I think getting `Baz test` is more naturally instead of `Foo test`, at least in this case.

**Comment by davidhesselbom** [comment]
> I think getting Baz test is more naturally instead of Foo test, at least in this case.

I agree. That's definitely not what I'd expected.

**Comment by fasterthanlime** [comment]
@zhaihj @davidhesselbom yes, and my proposal fixes that example too

**Comment by shamanas** [comment]
This seems to have already been fixed.  
Am I missing something or should I close the issue?

**Comment by shamanas** [comment]
I'm closing this since it seems to have been fixed.
